version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/coffee-cafe
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
      timeout: 300
  Install:
    - location: scripts/install.sh
      runas: root
      timeout: 600
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
      timeout: 300
  ValidateService:
    - location: scripts/validate.sh
      runas: root
      timeout: 120
